### ISSUE TITLE
Summarize the steps to reproduce this project for the PowerPoint Presentation

### ISSUE THREAD

**Issue by Tobyclark** [Tobyclark/BakerySalesTrendsAnalysis#6]
Summarize the steps to reproduce this project for the PowerPoint Presentation, including the following:

- Clearly describe all the details of the reproduced algorithms. Why do you choose these three algorithms? Describe the simulation results and observations.
- Will you be able to reproduce the same results as those reported in the original paper? If not, what do you think are the reasons?
- What you have learned from these different papers?

**Comment by MSNjoki** [comment]
[Reproduced Algorithms.pptx](https://github.com/Tobyclark/BakerySalesTrendsAnalysis/files/14971708/Reproduced.Algorithms.pptx)
